name: Jest Tests

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: alchemy
          POSTGRES_PASSWORD: alchemy
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test
      env:
        CI: true
        DATABASE_URL: postgres://alchemy:alchemy@postgres:5432/alchemy
        SALT_ROUNDS: ${{secrets.SALT_ROUNDS}}
        APP_SECRET: ${{secrets.APP_SECRET}}
        CLOUDINARY_CLOUD_NAME: ${{secrets.CLOUDINARY_CLOUD_NAME}}
        CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
        CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}
        CLOUDINARY_URL: ${{secrets.CLOUDINARY_URL}}
        MAPQUEST_KEY: ${{secrets.MAPQUEST_KEY}}
